
underlay:
    local:
        asn: 60016
    neighbors:
      - interface: et-0/0/48
        name: SPINE01
        asn: 60001
        peer_ip: 171.0.0.20
        local_ip: 171.0.0.21
      - interface: et-0/0/49
        name: SPINE02
        asn: 60002
        peer_ip: 171.0.0.22
        local_ip: 171.0.0.23
